POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "test",
  "idCard": "9999",
  "type": "1"
}
###

GET http://localhost:8000/member/passenger/query-list?page=1&size=2
Content-Type: application/json
token: {{token}}

###

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": "1983217934792790016",
  "memberId": "1981368266345549824",
  "name": "test666",
  "idCard": "9999",
  "type": "1"
}
###
